### PR TITLE
Correct generated client, bidi stream method stubs

### LINKED ISSUE #132: Client streaming stub generation uses wrong type
It seems to be using the responseType instead of the requesType, see https://github.com/improbable-eng/ts-protoc-gen/blob/51f57eaaafa0434433c218e40a7649fe095a46ea/src/service/grpcweb.ts#L534

### PR DESCRIPTION
**Pull request by johanbrandhorst**
It appears we were using the responseType instead of the requestType when creating the stream.

Fixes #132, #133

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
@jonny-improbable should be a simple merge I hope.

**Comment by johanbrandhorst** [comment]
I've found another problem, lets wait with merging this please.

**Comment by johanbrandhorst** [comment]
@jonny-improbable ok there we go.

File: src/service/grpcweb.ts [hunk 1]
```diff
@@ -222,13 +222,13 @@ function generateTypescriptDefinition(fileDescriptor: FileDescriptorProto, expor
   printer.printIndentedLn(`on(type: 'end', handler: () => void): RequestStream<T>;`);
   printer.printIndentedLn(`on(type: 'status', handler: (status: Status) => void): RequestStream<T>;`);
   printer.printLn(`}`);
-  printer.printLn(`interface BidirectionalStream<T> {`);
-  printer.printIndentedLn(`write(message: T): BidirectionalStream<T>;`);
+  printer.printLn(`interface BidirectionalStream<Req, Res> {`);
```
Comment (johanbrandhorst) [inline src/service/grpcweb.ts]: I'd like to know opinions on the Generic type variables here, but I can't use `<R, R>`, and I think `<T, V>` is just unclear.

Comment (johanbrandhorst) [reply src/service/grpcweb.ts]: Maybe `<ReqT, ResT>`?

**Comment by johanbrandhorst** [comment]
My formatter has formatted the files I've touched, I can try and revert those changes and keep the edits minimal if required.

File: src/service/grpcweb.ts (hunk 1 above)
Comment (jonnyreeves) [reply src/service/grpcweb.ts]: Yep ReqT and ResT work for me

**Comment by johanbrandhorst** [comment]
@jonnyreeves should be good now

**Comment by jonnyreeves** [comment]
Both work 😁

**Comment by jonnyreeves** [comment]
Published as (0.7.8-pre.217169b)
